### ISSUE TITLE
other add-on

### ISSUE THREAD

**Issue by ijgnd** [epiphanie-gedeon/anki-update-picker#1]
That's not an "issue" or bug report. I saw your add-on only after I finished doing something very similar last night:  see  [here](https://ankiweb.net/shared/info/1655214124) and  [here](https://github.com/ijgnd/anki__postpone_delay_addon_update_for_selected). 

[This reddit discussion](https://www.reddit.com/r/Anki/comments/gx3ocl/anki_addons_safe/) motivated me to work on this for myself and family/friends. I remember seeing this on a list by DRroscoe for Arthur (which DRroscoe forwarded to me) but since about a month passed I assumed that he had solved the situation in a simpler way (like renaming the addon folder). So I didn't expect than someone else would make such an add-on.

At the moment I have more features than what you've published. If there's anything in my version that's useful for you please recycle it. If a professional developer looks at my code and I see how you transform it I can only learn. My code is pretty basic and I copied&pasted from my other add-ons a lot but it seems to work (though there's a good chance that I have some bugs ...)

**Comment by epiphanie-gedeon** [comment]
Thanks for letting me know

Your addon does seem to have way more features, so I suggest we make it the main one. I will close this one and make pull request on yours if I find anything
